services:
  postgres:
    image: postgres:17
    container_name: test-postgres
    restart: always
    env_file:
      - .env
    ports:
      - "${OUTER_PORT}:${INTERNAL_PORT}"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 5s
      retries: 5
    volumes:
      - ./backup_1.sql:/docker-entrypoint-initdb.d/backup_1.sql